version: "3.2"

services:
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGODB_DATABASE: MONGODB_DATABASE
    container_name: CONTAINER_NAME
    ports:
      - CONTAINER_PORT:LOCAL_PORT

  mysql:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: MYSQL_DATABASE
    container_name: CONTAINER_NAME
    ports:
      - CONTAINER_PORT:LOCAL_PORT